version: "3"
services:
  mysql:
    container_name: sample-mysql
    image: mysql:8.0
    env_file: ./.env
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/my.conf:/etc/mysql/conf.d/my.conf
    ports:
      - "7102:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    networks:
      - sample

  phpmyadmin:
    container_name: sample-phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 7103:80
    env_file: ./.env
    depends_on:
      - mysql
    networks:
      - sample

  api:
    container_name: sample-api
    build: ./api
    volumes:
      - ./api/src:/var/www/html
    ports:
      - "7101:80"
    depends_on:
      - mysql
    networks:
      - sample

  client:
    container_name: sample-vue
    build: ./client
    ports:
      - "7100:80"
    depends_on:
      - api
    networks:
      - sample

volumes:
  mysql:

networks:
  sample:
    driver: bridge
